INSERT INTO public.professionals (name, specialty, credentials, bio, rating, availability, price_range) VALUES
  ('Dr. Sarah Johnson', 'Psychologist', 'PhD, Licensed Clinical Psychologist', 'Specializing in cognitive behavioral therapy and anxiety disorders with over 15 years of experience helping clients achieve mental wellness.', 4.9, ARRAY['Monday', 'Wednesday', 'Friday'], '$150-200/session'),
  ('Dr. Michael Chen', 'Psychologist', 'PsyD, LMFT', 'Expert in family therapy and relationship counseling. Passionate about helping individuals and couples build stronger connections.', 4.8, ARRAY['Tuesday', 'Thursday', 'Saturday'], '$120-180/session'),
  ('Dr. Emily Rodriguez', 'Psychiatrist', 'MD, Board Certified Psychiatrist', 'Comprehensive psychiatric care including medication management and therapy for depression, anxiety, and bipolar disorder.', 4.9, ARRAY['Monday', 'Tuesday', 'Thursday'], '$200-300/session'),
  ('Dr. James Williams', 'Psychiatrist', 'MD, Child & Adolescent Psychiatry', 'Specialized in treating children and adolescents with ADHD, autism spectrum disorders, and mood disorders.', 4.7, ARRAY['Wednesday', 'Friday'], '$180-250/session'),
  ('Lisa Anderson', 'Life Coaching', 'ICF Certified Life Coach', 'Empowering individuals to discover their purpose and achieve their personal and professional goals through transformative coaching.', 4.8, ARRAY['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'], '$80-120/session'),
  ('Mark Thompson', 'Life Coaching', 'Executive Coach, MBA', 'Helping professionals navigate career transitions and develop leadership skills for lasting success.', 4.6, ARRAY['Tuesday', 'Thursday', 'Saturday'], '$100-150/session'),
  ('Rachel Green', 'Nutrition', 'RD, Certified Nutritionist', 'Holistic approach to nutrition focusing on mental health, gut-brain connection, and sustainable lifestyle changes.', 4.9, ARRAY['Monday', 'Wednesday', 'Friday'], '$90-130/session'),
  ('David Kim', 'Nutrition', 'MS, Sports Nutritionist', 'Integrating nutrition science with mental wellness to optimize both physical and mental performance.', 4.7, ARRAY['Tuesday', 'Thursday', 'Saturday'], '$85-125/session')
ON CONFLICT DO NOTHING;